/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'elvis' at '6/25/17 10:06 PM' with Gradle 3.1
 *
 * @author elvis, @date 6/25/17 10:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
